CREATE TABLE USUARIOS
(
ID_USUARIO INT IDENTITY(1,1),
NOMBRE VARCHAR (100),
CONTRASEÑA VARBINARY (8000),
EMAIL VARCHAR (100),
ESADMIN BIT
CONSTRAINT PK_USUARIOS PRIMARY KEY (ID_USUARIO) 

)

SELECT * FROM USUARIOS;


CREATE PROCEDURE REGISTRAR_USUARIOS
@NOMBRE VARCHAR (100),
@EMAIL VARCHAR (100),
@ESADMIN BIT,
@CONTRASEÑA VARCHAR (50)
AS 
BEGIN
INSERT INTO USUARIOS (NOMBRE,EMAIL,ESADMIN,CONTRASEÑA) VALUES (@NOMBRE,@EMAIL,@ESADMIN,ENCRYPTBYPASSPHRASE('password',@CONTRASEÑA))
END;



ALTER PROCEDURE [dbo].[LOGGIN_USUARIOS]
@EMAIL VARCHAR (100),
@PASSWORD VARCHAR (100) OUTPUT
AS
BEGIN
SELECT @PASSWORD = CONVERT(VARCHAR(MAX),DECRYPTBYPASSPHRASE('password',CONTRASEÑA)) FROM USUARIOS WHERE EMAIL = @EMAIL
END