ALTER PROCEDURE [dbo].[GET_USERS]
AS 
SELECT * FROM USUARIOS;


CREATE PROCEDURE DELETE_USERS
@ID INT
AS
BEGIN
DELETE FROM USUARIOS WHERE ID_USUARIO = @ID
END

CREATE PROCEDURE CREATE_ADMINISTRATOR
@EMAIL VARCHAR(100)
AS
BEGIN
UPDATE USUARIOS SET ESADMIN = 'TRUE' WHERE EMAIL = @EMAIL
END

CREATE PROCEDURE DELETE_ADMINISTRATOR
@EMAIL VARCHAR(100)
AS
BEGIN
UPDATE USUARIOS SET ESADMIN = 'FALSE' WHERE EMAIL = @EMAIL
END

EXEC CREATE_ADMINISTRATOR 'gbritos13@gmail.com';

SELECT * FROM PRODUCTOS;

CREATE PROCEDURE GET_PRODUCT_ID
@ID INT
AS 
BEGIN
SELECT * FROM PRODUCTOS WHERE ID_PRODUCTO = @ID
END;

EXEC GET_PRODUCT_ID 5;

UPDATE USUARIOS SET ESADMIN = 'TRUE' WHERE ID_USUARIO = 5;

SELECT * FROM USUARIOS;

SELECT * FROM PRODUCTOS;

CREATE PROCEDURE POST_PRODUCTOS
@IDMARCA INT,
@IDRUBRO INT,
@NOMBRE VARCHAR (100),
@DESCRIPCION VARCHAR (100),
@PRECIO MONEY ,
@STOCK INT, 
@STOCKMINIMO INT
AS
BEGIN 
INSERT INTO PRODUCTOS (ID_MARCA,ID_RUBRO,NOMBRE,DESCRIPCION,PRECIO,STOCK,STOCK_MINIMO) VALUES (@IDMARCA,@IDRUBRO,@NOMBRE,@DESCRIPCION,@PRECIO,@STOCK,@STOCKMINIMO)
END 


CREATE PROCEDURE DELETE_PRODUCTS
@ID INT
AS
BEGIN
DELETE FROM PRODUCTOS WHERE ID_PRODUCTO = @ID
END

CREATE PROCEDURE GET_ORDERS
AS
BEGIN
SELECT * FROM PEDIDOS
END;


EXEC GET_ORDERS;

CREATE PROCEDURE GET_ORDER_ID
@ID INT
AS
BEGIN
SELECT * FROM PEDIDOS WHERE ID_PEDIDO = @ID
END;

EXEC GET_ORDER_ID 5

CREATE PROCEDURE POST_ORDER
@IDPROVEEDOR INT,
@IDSUCURSAL INT,
@IDENTREGA INT,
@IDTIPOSOLICITUD INT,
@IDEMPLEADORECEPTOR INT,
@FECHAPEDIDO DATETIME,
@HORAPEDIDO DATETIME,
@FECHAENTREGAPEDIDO DATETIME,
@PLAZOENTREGAPEDIDO DATETIME,
@IDCLIENTE INT,
@ID_PEDIDO INT OUTPUT
AS 
BEGIN
INSERT INTO PEDIDOS (ID_PROVEEDOR,ID_SUCURSAL,ID_ENTREGA,ID_TIPO_SOLICITUD,ID_EMPLEADO_RECEPTOR,FECHA_PEDIDO,HORA_PEDIDO,FECHA_ENTREGA_PEDIDO,PLAZO_ENTREGA_PEDIDO,ID_CLIENTE)
VALUES(@IDPROVEEDOR,@IDSUCURSAL,@IDENTREGA,@IDTIPOSOLICITUD,@IDEMPLEADORECEPTOR,@FECHAPEDIDO,@HORAPEDIDO,@FECHAENTREGAPEDIDO,@PLAZOENTREGAPEDIDO,@IDCLIENTE)
SET @ID_PEDIDO = SCOPE_IDENTITY();
END;


SELECT * FROM DETALLES_PEDIDOS;


CREATE PROCEDURE POST_ORDER_DETAIL
@@IDPEDID INT,
@IDPRODUCTO INT,
@CANTIDAD INT,
@PRECIO MONEY
AS 
BEGIN
INSERT INTO DETALLES_PEDIDOS (ID_PEDIDO,ID_PRODUCTO,CANTIDAD,IMPORTE) VALUES (@IDPEDIDO,@IDPRODUCTO,@CANTIDAD,@PRECIO)
END;


CREATE PROCEDURE CARGAR_PROVEEDORES
AS 
BEGIN 
SELECT * FROM PROVEEDORES
END;

EXEC CARGAR_PROVEEDORES


CREATE PROCEDURE CARGAR_SUCURSALES
AS 
BEGIN 
SELECT * FROM SUCURSALES
END;

CREATE PROCEDURE CARGAR_ENTREGAS
AS
BEGIN
SELECT * FROM ENTREGAS
END;

CREATE PROCEDURE CARGAR_TIPOS_SOLICTIDES 
AS
BEGIN
SELECT * FROM SOLICITUDES_PEDIDOS
END;


CREATE PROCEDURE CARGAR_EMPLEADOS
AS
BEGIN
SELECT * FROM EMPLEADOS
END;


--ALTER PROCEDURE DELETE_USERS
--@EMAIL VARCHAR (100)
--AS 
--BEGIN
--DELETE FROM USUARIOS WHERE EMAIL = @EMAIL
--END;

--CREATE PROCEDURE GET_CLIENTS
--AS
--BEGIN
--SELECT * FROM CLIENTES
--END;

CREATE PROCEDURE LISTAR_PEDIDOS
AS 
BEGIN
SELECT
P.ID_PEDIDO AS 'Pedidos',
PR.NOMBRE AS 'Proveedores',
S.DIRECCION_SUCURSAL AS 'Sucursales',
E.DESCRIPCION AS 'Entregas',
SP.SOLICITADO_VIA AS 'Solicitado Via',
EMP.NOMBRE AS 'Empleados',
C.NOMBRE + ' ' +  C.APELLIDO AS 'Clientes'
FROM PEDIDOS P
JOIN PROVEEDORES PR ON PR.ID_PROVEEDOR = P.ID_PROVEEDOR
JOIN SUCURSALES S ON S.ID_SUCURSAL = P.ID_SUCURSAL
JOIN ENTREGAS E ON E.ID_ENTREGA = P.ID_ENTREGA
JOIN SOLICITUDES_PEDIDOS SP ON SP.ID_SOLICITUD = P.ID_TIPO_SOLICITUD
JOIN EMPLEADOS EMP ON EMP.ID_EMPLEADO = P.ID_EMPLEADO_RECEPTOR
JOIN CLIENTES C ON C.ID_CLIENTE = P.ID_CLIENTE
END

ALTER PROCEDURE LISTAR_PEDIDOS
AS 
BEGIN
SELECT DISTINCT
P.ID_PEDIDO AS 'Pedidos',
PR.NOMBRE AS 'Proveedores',
S.DIRECCION_SUCURSAL AS 'Sucursales',
E.DESCRIPCION AS 'Entregas',
SP.SOLICITADO_VIA AS 'Solicitado Via',
EMP.NOMBRE AS 'Empleados',
C.NOMBRE + ' ' +  C.APELLIDO AS 'Clientes',
P.HORA_PEDIDO AS 'Hora Pedido',
P.FECHA_PEDIDO AS 'Fecha Pedido'
FROM PEDIDOS P
JOIN PROVEEDORES PR ON PR.ID_PROVEEDOR = P.ID_PROVEEDOR
JOIN SUCURSALES S ON S.ID_SUCURSAL = P.ID_SUCURSAL
JOIN ENTREGAS E ON E.ID_ENTREGA = P.ID_ENTREGA
JOIN SOLICITUDES_PEDIDOS SP ON SP.ID_SOLICITUD = P.ID_TIPO_SOLICITUD
JOIN EMPLEADOS EMP ON EMP.ID_EMPLEADO = P.ID_EMPLEADO_RECEPTOR
JOIN CLIENTES C ON C.ID_CLIENTE = P.ID_CLIENTE
END
