
-- CREATE DATABASE RECETAS_II;

-- USE RECETAS_II;

-- CREATE TABLE INGREDIENTES
-- (
--     ID_INGREDIENTE INT IDENTITY(1,1),
--     INGREDIENTE VARCHAR (50),
--     CONSTRAINT PK_INGREDIENTE PRIMARY KEY (ID_INGREDIENTE)


-- )

-- CREATE TABLE TIPOS_RECETAS
-- (
--     ID_TIPO_RECETA INT IDENTITY(1,1),
--     TIPO_RECETA VARCHAR (50),
--     CONSTRAINT PK_TIPO_RECETA PRIMARY KEY (ID_TIPO_RECETA)


-- )

-- CREATE TABLE RECETAS
-- (
--     ID_RECETA INT IDENTITY (1,1),
--     ID_TIPO_RECETA INT,
--     NOMBRE VARCHAR (50),
--     CHEFF VARCHAR (50)
--         CONSTRAINT PK_RECETA PRIMARY KEY (ID_RECETA),
--     CONSTRAINT FK_TIPOS_RECETA_RECETA FOREIGN KEY (ID_TIPO_RECETA) REFERENCES TIPOS_RECETAS


-- )





-- CREATE TABLE DETALLES_RECETAS
-- (
--     ID_DETALLE_RECETA INT IDENTITY(1,1),
--     ID_RECETA INT ,
--     ID_INGREDIENTE INT ,
--     CANTIDAD INT,
--     CONSTRAINT PK_DETALLE_RECETA PRIMARY KEY (ID_DETALLE_RECETA),
--     CONSTRAINT FK_DETALLE_RECETA_RECETA FOREIGN KEY (ID_RECETA) REFERENCES RECETAS,
--     CONSTRAINT FK_INGREDIENTE_DETALLE_RECETA FOREIGN KEY (ID_INGREDIENTE) REFERENCES INGREDIENTES


-- )



-- CREATE PROCEDURE SP_CONSULTAR_TIPOS_RECETAS
-- AS 
-- BEGIN 
-- SELECT * FROM TIPOS_RECETAS
-- END ;

-- INSERT INTO TIPOS_RECETAS VALUES ('MEXICANA')

-- INSERT INTO TIPOS_RECETAS VALUES ('CHINA')

-- INSERT INTO TIPOS_RECETAS VALUES ('USA')

-- EXEC SP_CONSULTAR_TIPOS_RECETAS;

-- SELECT * FROM INGREDIENTES;

-- SELECT * FROM INGREDIENTES;

-- ALTER TABLE INGREDIENTES  ADD UNIDAD INT;


-- INSERT INTO INGREDIENTES (INGREDIENTE) VALUES ('SAL');

-- INSERT INTO INGREDIENTES (INGREDIENTE) VALUES ('PIMIENTA');

-- INSERT INTO INGREDIENTES (INGREDIENTE) VALUES ('HARINA');

-- INSERT INTO INGREDIENTES (INGREDIENTE) VALUES ('HUEVO');


-- CREATE PROCEDURE SP_CONSULTAR_INGREDIENTES
-- AS 
-- BEGIN 
-- SELECT * FROM INGREDIENTES 
-- END;

-- SELECT * FROM RECETAS;

-- CREATE PROCEDURE SP_INSERTAR_RECETA
-- 	@NOMBRE varchar(50),
--     @CHEFF varchar(100),
--     @ID_TIPO_RECETA int,
-- 	@ID_RECETA int OUTPUT
-- AS
-- BEGIN
-- 	INSERT INTO RECETAS (NOMBRE, CHEFF, ID_TIPO_RECETA)
--     VALUES (@NOMBRE, @CHEFF, @ID_TIPO_RECETA );

-- 	SET @ID_RECETA = SCOPE_IDENTITY();

-- END
-- GO

-- SELECT * FROM DETALLES_RECETAS;

-- CREATE PROCEDURE SP_INSERTAR_DETALLE 
-- @ID_RECETA INT,
-- @ID_INGREDIENTE INT,
-- @CANTIDAD INT
-- AS 
-- BEGIN 
-- INSERT INTO DETALLES_RECETAS (ID_RECETA,ID_INGREDIENTE,CANTIDAD)
-- VALUES(@ID_RECETA,@ID_INGREDIENTE,@CANTIDAD)
-- END


CREATE PROCEDURE SP_NEXT_RECETA 
AS 
BEGIN 
SELECT MAX(ID_RECETA) FROM RECETAS 
END;

EXEC SP_NEXT_RECETA;