USE LIBRERIA_LCI_II;

-- CREATE FUNCTION PALABRA 
-- (@descripcion VARCHAR (100) = 'pa')
-- RETURNS TABLE 
-- AS
-- RETURN (SELECT descripcion ,pre_unitario
-- FROM ARTICULOS WHERE descripcion LIKE @descripcion + '%' )

/*TABLA EN LINEA
 LAS QUE NO SEAN TABLA EN LINEA, TIENE QUE ESPECIFICAR LOS CAMPOS...*/
-- SELECT * FROM PALABRA(DEFAULT);

 


/*CREATE FUNCTION DEVOLVER_ARTICULOS_TABLAS (@DESC VARCHAR (100))

RETURNS @TABLAARTICULOS TABLE
(DESCRIPCION VARCHAR (100))
AS 
BEGIN 
INSERT @TABLAARTICULOS
SELECT DESCRIPCION FROM ARTIUCLOS
WHERE DESCRIPCION LIKE '%' + @DESCRIPCION + '%'
RETURN END 


SELECT * FROM DEVOLVER_ARTICULOS_TABLAS('LAPIZ')*/




/* CREATE PROCEDURE PA_ARTICULOS_DESCRIPCION
@DESCRIPCION VARCHAR (100) = NULL
AS 
IF @DESCRIPCION IS NULL 
BEGIN 
SELECT 'DEBE INDICAR UNA DESCRIPCION'
RETURN 
END;
SELECT descripcion,pre_unitario,observaciones
FROM ARTICULOS 
WHERE descripcion like @descripcion */


/*STOCK MENOR A 50*/



SELECT * FROM ARTICULOS;



-- ALTER PROCEDURE MENOR_STOCK
-- @STOCK INT  
-- AS 
-- IF @STOCK > 50 
-- BEGIN 
-- SELECT 'DEBE INDICAR UN STOCK '
-- RETURN 
-- END;


-- SELECT descripcion,pre_unitario,observaciones
-- FROM ARTICULOS 
-- WHERE STOCK > 50 


-- EXEC MENOR_STOCK;


-- BEGIN TRY 
-- EXEC PA_ARTICULOS_DESCRIPCION;
-- --SELECT 15/0 AS ERROR; 
-- END TRY 
-- BEGIN CATCH 
-- SELECT 'SE PRODUJO EL SIGUIENTE ERROR',
-- ERROR_NUMBER() AS NUMERO , 
-- ERROR_STATE()  AS ESTADO, 
-- ERROR_SEVERITY() AS GRAVEDAD, 
-- ERROR_PROCEDURE() AS PROCEDIMIENTO,
-- ERROR_LINE() AS LINEA, 
-- ERROR_MESSAGE() AS MENSAJE; 
-- END CATCH;


-- DECLARE @ERR INT 
-- SELECT 1/0 AS ERROR; 
-- SELECT @ERR = @@error
-- if @err != 0
-- PRINT 'EL NRO DE ERROR ES: ' + ltrim (str(@err)) 



-- SELECT * FROM sys.messages;







/*

UNIDAD 4

HACER ESTE EJERCICIO Y ENVIARLO POR FORO 

4-3-1-E


*/



/*Mostrar el nombre del cliente al que se le realizó la primer venta en un
parámetro de salida*/


-- USE LIBRERIA_LCI_II;

-- CREATE PROCEDURE FIRST_CLIENT
-- @name VARCHAR (50) OUTPUT
-- AS
-- SELECT  top 1 @name = C.nom_cliente
-- FROM FACTURAS F 
-- JOIN CLIENTES C ON C.cod_cliente = F.cod_cliente
-- ORDER BY F.FECHA ASC;


-- DECLARE @SALIENDO VARCHAR (50)  ;

-- EXEC FIRST_CLIENT2 @SALIENDO OUTPUT;

-- SELECT @SALIENDO AS 'CLIENTE';

