CREATE DATABASE TPII_PROGRAMACION_II;

USE TPII_PROGRAMACION_II;

CREATE TABLE FORMAS_PAGOS
(
    idFormaPago INT IDENTITY (1,1),
    nombre VARCHAR (30),
    CONSTRAINT PK_FORMA_PAGO PRIMARY KEY (idFormaPago)
);

CREATE TABLE ARTICULOS
(
    id_articulo INT IDENTITY (1,1),
    nombre VARCHAR (20),
    precioUnitario DECIMAL (10,2),
    CONSTRAINT PK_ARTICULO PRIMARY KEY (id_articulo)

)

CREATE TABLE FACTURAS
(
    id_factura INT IDENTITY(1,1),
    fecha DATETIME,
    idFormaPago INT ,
    cliente VARCHAR (20),
    CONSTRAINT PK_FACTURAS PRIMARY KEY (id_factura),
    CONSTRAINT FK_FORMA_PAGO FOREIGN KEY (idFormaPago) REFERENCES FORMAS_PAGOS (idFormaPago)

);


CREATE TABLE DETALLES_FACTURAS
(
    id_detalle INT IDENTITY(1,1),
    id_articulo INT ,
    id_factura INT ,
    cantidad INT,
    CONSTRAINT PK_DETALLE_FACTURA PRIMARY KEY (id_detalle),
    CONSTRAINT FK_FACTURA_DETALLE_FACTURA FOREIGN KEY (id_factura) REFERENCES FACTURAS (id_factura),
    CONSTRAINT FK_ARTICULO_DETALLE_FACTURA FOREIGN KEY (id_articulo) REFERENCES ARTICULOS (id_articulo)


);

INSERT INTO FORMAS_PAGOS VALUES ('EFECTIVO');
INSERT INTO FORMAS_PAGOS VALUES ('DEBITO');
INSERT INTO FORMAS_PAGOS VALUES ('CREDITO');

