
--############################# PROVINCIAS #############################################################
-- ALTER TABLE PROVINCIAS ALTER COLUMN NOMBRE VARCHAR (100);
-- INSERT INTO PROVINCIAS  (ID_PAIS,NOMBRE) VALUES (3,'Provincia de Buenos Aires');
-- INSERT INTO PROVINCIAS  (ID_PAIS,NOMBRE) VALUES (3,'Provincia de Catamarca');
-- INSERT INTO PROVINCIAS  (ID_PAIS,NOMBRE) VALUES (3,'Provincia del Chaco');
-- INSERT INTO PROVINCIAS  (ID_PAIS,NOMBRE) VALUES (3,'Provincia del Chubut');
-- INSERT INTO PROVINCIAS  (ID_PAIS,NOMBRE) VALUES (3,'Provincia de Córdoba');
-- INSERT INTO PROVINCIAS  (ID_PAIS,NOMBRE) VALUES (3,'Provincia de Corrientes');
-- INSERT INTO PROVINCIAS  (ID_PAIS,NOMBRE) VALUES (3,'Provincia de Entre Ríos');
-- INSERT INTO PROVINCIAS  (ID_PAIS,NOMBRE) VALUES (3,'Provincia de Formosa');
-- INSERT INTO PROVINCIAS  (ID_PAIS,NOMBRE) VALUES (3,'Provincia de Jujuy');
-- INSERT INTO PROVINCIAS  (ID_PAIS,NOMBRE) VALUES (3,'Provincia de La Rioja');
-- INSERT INTO PROVINCIAS  (ID_PAIS,NOMBRE) VALUES (3,'Provincia de La Pampa');
-- INSERT INTO PROVINCIAS  (ID_PAIS,NOMBRE) VALUES (3,'Provincia de Mendoza');
-- INSERT INTO PROVINCIAS  (ID_PAIS,NOMBRE) VALUES (3,'Provincia de Misiones');
-- INSERT INTO PROVINCIAS  (ID_PAIS,NOMBRE) VALUES (3,'Provincia de Río Negro');
-- INSERT INTO PROVINCIAS  (ID_PAIS,NOMBRE) VALUES (3,'Provincia de Salta');
-- INSERT INTO PROVINCIAS  (ID_PAIS,NOMBRE) VALUES (3,'Provincia de San Juan'); 
-- INSERT INTO PROVINCIAS  (ID_PAIS,NOMBRE) VALUES (3,'Provincia de San Luis'); 
-- INSERT INTO PROVINCIAS  (ID_PAIS,NOMBRE) VALUES (3,'Provincia de Santa Cruz'); 
-- INSERT INTO PROVINCIAS  (ID_PAIS,NOMBRE) VALUES (3,'Provincia de Santa Fe'); 
-- INSERT INTO PROVINCIAS  (ID_PAIS,NOMBRE) VALUES (3,'Provincia de Santiago del Estero'); 
-- INSERT INTO PROVINCIAS  (ID_PAIS,NOMBRE) VALUES (3,'Provincia de Tierra del Fuego, Antártida e Islas del Atlántico Sur'); 
-- INSERT INTO PROVINCIAS  (ID_PAIS,NOMBRE) VALUES (3,'Provincia de Tucumán');
-- INSERT INTO PROVINCIAS  (ID_PAIS,NOMBRE) VALUES (3,'Provincia de Neuquén');

--############################# CIUDADES ################################################################
-- INSERT INTO CIUDADES  (ID_PROVINCIA,NOMBRE) VALUES (1,'La Plata');
-- INSERT INTO CIUDADES  (ID_PROVINCIA,NOMBRE) VALUES (23,'San Fernando del Valle de Catamarca');
-- INSERT INTO CIUDADES  (ID_PROVINCIA,NOMBRE) VALUES (24,'Resistencia');
-- INSERT INTO CIUDADES  (ID_PROVINCIA,NOMBRE) VALUES (25,'Rawson');
-- INSERT INTO CIUDADES  (ID_PROVINCIA,NOMBRE) VALUES (26,'Córdoba');
-- INSERT INTO CIUDADES  (ID_PROVINCIA,NOMBRE) VALUES (27,'Corrientes');
-- INSERT INTO CIUDADES  (ID_PROVINCIA,NOMBRE) VALUES (28,'Paraná');
-- INSERT INTO CIUDADES  (ID_PROVINCIA,NOMBRE) VALUES (29,'Formosa');
-- INSERT INTO CIUDADES  (ID_PROVINCIA,NOMBRE) VALUES (30,'San Salvador de Jujuy');
-- INSERT INTO CIUDADES  (ID_PROVINCIA,NOMBRE) VALUES (31,'La Rioja');
-- INSERT INTO CIUDADES  (ID_PROVINCIA,NOMBRE) VALUES (32,'Santa Rosa');
-- INSERT INTO CIUDADES  (ID_PROVINCIA,NOMBRE) VALUES (33,'Mendoza');
-- INSERT INTO CIUDADES  (ID_PROVINCIA,NOMBRE) VALUES (34,'Posadas');
-- INSERT INTO CIUDADES  (ID_PROVINCIA,NOMBRE) VALUES (35,'Viedma');
-- INSERT INTO CIUDADES  (ID_PROVINCIA,NOMBRE) VALUES (36,'Salta'); 
-- INSERT INTO CIUDADES  (ID_PROVINCIA,NOMBRE) VALUES (37,'San Juan'); 
-- INSERT INTO CIUDADES  (ID_PROVINCIA,NOMBRE) VALUES (38,'San Luis'); 
-- INSERT INTO CIUDADES  (ID_PROVINCIA,NOMBRE) VALUES (39,'Río Gallegos'); 
-- INSERT INTO CIUDADES  (ID_PROVINCIA,NOMBRE) VALUES (40,'Santa Fe de la Vera Cruz'); 
-- INSERT INTO CIUDADES  (ID_PROVINCIA,NOMBRE) VALUES (41,'Santiago del Estero');
-- INSERT INTO CIUDADES  (ID_PROVINCIA,NOMBRE) VALUES (43,'San Miguel de Tucumán'); 
-- INSERT INTO CIUDADES  (ID_PROVINCIA,NOMBRE) VALUES (45,'Ushuaia');
-- INSERT INTO CIUDADES  (ID_PROVINCIA,NOMBRE) VALUES (46,'Neuquén');
	
--############################# BARRIOS #################################################################

-- INSERT INTO BARRIOS  (ID_CIUDAD,NOMBRE) VALUES (6,'1 de mayo');
-- INSERT INTO BARRIOS  (ID_CIUDAD,NOMBRE) VALUES (6,'16 de noviembre');
-- INSERT INTO BARRIOS  (ID_CIUDAD,NOMBRE) VALUES (6,'2 de septiembre');
-- INSERT INTO BARRIOS  (ID_CIUDAD,NOMBRE) VALUES (6,'20 de junio');
-- INSERT INTO BARRIOS  (ID_CIUDAD,NOMBRE) VALUES (6,'23 de abril');
-- INSERT INTO BARRIOS  (ID_CIUDAD,NOMBRE) VALUES (6,'4 de febrero');
-- INSERT INTO BARRIOS  (ID_CIUDAD,NOMBRE) VALUES (6,'Achaval Peña');
-- INSERT INTO BARRIOS  (ID_CIUDAD,NOMBRE) VALUES (6,'Acosta');
-- INSERT INTO BARRIOS  (ID_CIUDAD,NOMBRE) VALUES (6,'Aeronáutico');
-- INSERT INTO BARRIOS  (ID_CIUDAD,NOMBRE) VALUES (6,'Alberdi');
-- INSERT INTO BARRIOS  (ID_CIUDAD,NOMBRE) VALUES (6,'Alborada Norte');
-- INSERT INTO BARRIOS  (ID_CIUDAD,NOMBRE) VALUES (6,'Alborada Sur');
-- INSERT INTO BARRIOS  (ID_CIUDAD,NOMBRE) VALUES (6,'Alejandro Centeno');
-- INSERT INTO BARRIOS  (ID_CIUDAD,NOMBRE) VALUES (6,'Almirante Brown');
-- INSERT INTO BARRIOS  (ID_CIUDAD,NOMBRE) VALUES (6,'Alta Córdoba');
-- INSERT INTO BARRIOS  (ID_CIUDAD,NOMBRE) VALUES (6,'Altamira');
-- INSERT INTO BARRIOS  (ID_CIUDAD,NOMBRE) VALUES (6,'Alto Alberdi');
-- INSERT INTO BARRIOS  (ID_CIUDAD,NOMBRE) VALUES (6,'Alto Hermoso');
-- INSERT INTO BARRIOS  (ID_CIUDAD,NOMBRE) VALUES (6,'Alto Palermo');
-- INSERT INTO BARRIOS  (ID_CIUDAD,NOMBRE) VALUES (6,'Alto Verde');
-- INSERT INTO BARRIOS  (ID_CIUDAD,NOMBRE) VALUES (6,'Altos de Vélez Sársfield');
-- INSERT INTO BARRIOS  (ID_CIUDAD,NOMBRE) VALUES (6,'Altos de Villa Cabrera');
-- INSERT INTO BARRIOS  (ID_CIUDAD,NOMBRE) VALUES (6,'Altos San Martín');
-- INSERT INTO BARRIOS  (ID_CIUDAD,NOMBRE) VALUES (6,'Altos Sud de San Vicente');
-- INSERT INTO BARRIOS  (ID_CIUDAD,NOMBRE) VALUES (6,'Ameghino Norte');
-- INSERT INTO BARRIOS  (ID_CIUDAD,NOMBRE) VALUES (6,'Ameghino Sud');
-- INSERT INTO BARRIOS  (ID_CIUDAD,NOMBRE) VALUES (6,'Ampliación 1 De Mayo');
-- INSERT INTO BARRIOS  (ID_CIUDAD,NOMBRE) VALUES (6,'Ampliación Altamira');
-- INSERT INTO BARRIOS  (ID_CIUDAD,NOMBRE) VALUES (6,'Ampliación Benjamin Matienzo');
-- INSERT INTO BARRIOS  (ID_CIUDAD,NOMBRE) VALUES (6,'Ampliación Cerveceros');
-- INSERT INTO BARRIOS  (ID_CIUDAD,NOMBRE) VALUES (6,'Ampliación Empalme');
-- INSERT INTO BARRIOS  (ID_CIUDAD,NOMBRE) VALUES (6,'Ampliación Farina');
-- INSERT INTO BARRIOS  (ID_CIUDAD,NOMBRE) VALUES (6,'Ampliación Jardín Espinosa');
-- INSERT INTO BARRIOS  (ID_CIUDAD,NOMBRE) VALUES (6,'Ampliación Kennedy');
-- INSERT INTO BARRIOS  (ID_CIUDAD,NOMBRE) VALUES (6,'Ampliación Las Palmas');
-- INSERT INTO BARRIOS  (ID_CIUDAD,NOMBRE) VALUES (6,'Bajada De Piedra');
-- INSERT INTO BARRIOS  (ID_CIUDAD,NOMBRE) VALUES (6,'Bajada San Roque');
-- INSERT INTO BARRIOS  (ID_CIUDAD,NOMBRE) VALUES (6,'Bajo Galan');
-- INSERT INTO BARRIOS  (ID_CIUDAD,NOMBRE) VALUES (6,'Bajo General Paz');
-- INSERT INTO BARRIOS  (ID_CIUDAD,NOMBRE) VALUES (6,'Bella Vista');
-- INSERT INTO BARRIOS  (ID_CIUDAD,NOMBRE) VALUES (6,'Bella Vista Oeste');
-- INSERT INTO BARRIOS  (ID_CIUDAD,NOMBRE) VALUES (6,'Betania');
-- INSERT INTO BARRIOS  (ID_CIUDAD,NOMBRE) VALUES (6,'Bialet Masse');
-- INSERT INTO BARRIOS  (ID_CIUDAD,NOMBRE) VALUES (6,'Boedo');
-- INSERT INTO BARRIOS  (ID_CIUDAD,NOMBRE) VALUES (6,'California');
-- INSERT INTO BARRIOS  (ID_CIUDAD,NOMBRE) VALUES (6,'Caceres');
-- INSERT INTO BARRIOS  (ID_CIUDAD,NOMBRE) VALUES (6,'Cabo Farina');
-- INSERT INTO BARRIOS  (ID_CIUDAD,NOMBRE) VALUES (6,'Cabaña del Pilar');
-- INSERT INTO BARRIOS  (ID_CIUDAD,NOMBRE) VALUES (6,'Camino A Villa Posse');
-- INSERT INTO BARRIOS  (ID_CIUDAD,NOMBRE) VALUES (6,'Carbo');
-- INSERT INTO BARRIOS  (ID_CIUDAD,NOMBRE) VALUES (6,'Carola Lorenzini');
-- INSERT INTO BARRIOS  (ID_CIUDAD,NOMBRE) VALUES (6,'Ducasse');
-- INSERT INTO BARRIOS  (ID_CIUDAD,NOMBRE) VALUES (6,'Dean Funes');
-- INSERT INTO BARRIOS  (ID_CIUDAD,NOMBRE) VALUES (6,'De Los Bioquímicos');
-- INSERT INTO BARRIOS  (ID_CIUDAD,NOMBRE) VALUES (6,'Ejército Argentino');
-- INSERT INTO BARRIOS  (ID_CIUDAD,NOMBRE) VALUES (6,'El Cabildo');
-- INSERT INTO BARRIOS  (ID_CIUDAD,NOMBRE) VALUES (6,'El Cerrito');
-- INSERT INTO BARRIOS  (ID_CIUDAD,NOMBRE) VALUES (6,'El Pueblito');
-- INSERT INTO BARRIOS  (ID_CIUDAD,NOMBRE) VALUES (6,'El Quebracho');

----############################# PROVEEDORES ###########################################################

-- ALTER TABLE PROVEEDORES ALTER COLUMN DIRECCION_PROVEEDOR VARCHAR(100);
-- INSERT INTO PROVEEDORES (ID_BARRIO,NOMBRE,DIRECCION_PROVEEDOR) VALUES (1,'FCA Automobiles Argentina ','C.M. Della Paolera 299 - Piso 25');
-- INSERT INTO PROVEEDORES (ID_BARRIO,NOMBRE,DIRECCION_PROVEEDOR) VALUES (5,'Ford Argentina S.C.A. FORD Argentina','Av. Henry Ford y Ruta Panamericana 1617');
-- INSERT INTO PROVEEDORES (ID_BARRIO,NOMBRE,DIRECCION_PROVEEDOR) VALUES (7,'General Motors de Argentina S.R.L','Av. Del Libertador 101 1638');
-- INSERT INTO PROVEEDORES (ID_BARRIO,NOMBRE,DIRECCION_PROVEEDOR) VALUES (11,'Honda Motor de Argentina S.A','Av. del Libertador 1613');
-- INSERT INTO PROVEEDORES (ID_BARRIO,NOMBRE,DIRECCION_PROVEEDOR) VALUES (14,'Iveco Argentina S.A','Amaro Avalos 2829 - edificio 1 - Piso 4º');
-- INSERT INTO PROVEEDORES (ID_BARRIO,NOMBRE,DIRECCION_PROVEEDOR) VALUES (13,'Mercedes-Benz Argentina S.A','Sargento Cabral 3770');
-- INSERT INTO PROVEEDORES (ID_BARRIO,NOMBRE,DIRECCION_PROVEEDOR) VALUES (8,'Mercedes-Benz Camiones y Buses S.A.U','Sargento Cabral 3770');
-- INSERT INTO PROVEEDORES (ID_BARRIO,NOMBRE,DIRECCION_PROVEEDOR) VALUES (4,'Nissan Argentina S.A.','Av. del Libertador 174, Piso 2º');
-- INSERT INTO PROVEEDORES (ID_BARRIO,NOMBRE,DIRECCION_PROVEEDOR) VALUES (3,'Peugeot Citroen Argentina S.A.','Juan Domingo Perón 1001');
-- INSERT INTO PROVEEDORES (ID_BARRIO,NOMBRE,DIRECCION_PROVEEDOR) VALUES (9,'Renault Argentina S.A','Fray Justo Santa María de Oro 1744');
-- INSERT INTO PROVEEDORES (ID_BARRIO,NOMBRE,DIRECCION_PROVEEDOR) VALUES (17,'Scania Argentina S.A','Ruta Panamericana Km. 34 Piedrabuena 5400');
-- INSERT INTO PROVEEDORES (ID_BARRIO,NOMBRE,DIRECCION_PROVEEDOR) VALUES (29,'Toyota Argentina S.A','Thomas edison 2659 Piso 2');
-- INSERT INTO PROVEEDORES (ID_BARRIO,NOMBRE,DIRECCION_PROVEEDOR) VALUES (31,'Volkswagen Argentina S.A','Av. de las Industrias 3101');

--############################# SUCURSALES ##############################################################

-- INSERT INTO SUCURSALES (ID_BARRIO,DIRECCION_SUCURSAL) VALUES (1,'Viamonte 1133 7° Piso');
-- INSERT INTO SUCURSALES (ID_BARRIO,DIRECCION_SUCURSAL) VALUES (5,'Dr Romang - 192');
-- INSERT INTO SUCURSALES (ID_BARRIO,DIRECCION_SUCURSAL) VALUES (7,'Paraná - 467 - 1');
-- INSERT INTO SUCURSALES (ID_BARRIO,DIRECCION_SUCURSAL) VALUES (11,'Almirón - 301');
-- INSERT INTO SUCURSALES (ID_BARRIO,DIRECCION_SUCURSAL) VALUES (14,'Garay 489');
-- INSERT INTO SUCURSALES (ID_BARRIO,DIRECCION_SUCURSAL) VALUES (13,'San Martín - 595');
-- INSERT INTO SUCURSALES (ID_BARRIO,DIRECCION_SUCURSAL) VALUES (8,'D Onofrio 158');
-- INSERT INTO SUCURSALES (ID_BARRIO,DIRECCION_SUCURSAL) VALUES (4,'J J Castelli - 1855');
-- INSERT INTO SUCURSALES (ID_BARRIO,DIRECCION_SUCURSAL) VALUES (3,'República Argentina 15');
-- INSERT INTO SUCURSALES (ID_BARRIO,DIRECCION_SUCURSAL) VALUES (9,'F Ameghino - 245');
-- INSERT INTO SUCURSALES (ID_BARRIO,DIRECCION_SUCURSAL) VALUES (17,'Av Italia - 150');
-- INSERT INTO SUCURSALES (ID_BARRIO,DIRECCION_SUCURSAL) VALUES (29,'Gral Paz - 1240');
-- INSERT INTO SUCURSALES (ID_BARRIO,DIRECCION_SUCURSAL) VALUES (31,'Av.Colon 1985');

--############################# ENTREGAS ################################################################

-- INSERT INTO ENTREGAS (DESCRIPCION) VALUES ('Entregar por la mañana');
-- INSERT INTO ENTREGAS (DESCRIPCION) VALUES ('Entregar al portero');
-- INSERT INTO ENTREGAS (DESCRIPCION) VALUES ('Casa Esquina');
-- INSERT INTO ENTREGAS (DESCRIPCION) VALUES ('Dejar en el kiosko de a lado');
-- INSERT INTO ENTREGAS (DESCRIPCION) VALUES ('Entregar después de las 14hs');
-- INSERT INTO ENTREGAS (DESCRIPCION) VALUES ('El timbre no funciona llamar por telefono');
-- INSERT INTO ENTREGAS (DESCRIPCION) VALUES ('Porter 4B');
-- INSERT INTO ENTREGAS (DESCRIPCION) VALUES ('Es una quiniela');
-- INSERT INTO ENTREGAS (DESCRIPCION) VALUES ('Frente a la Plaza');
-- INSERT INTO ENTREGAS (DESCRIPCION) VALUES ('Es una calle sin salida');
-- INSERT INTO ENTREGAS (DESCRIPCION) VALUES ('Es un pasaje');

--############################# PEDIDOS #################################################################

-- INSERT INTO SOLICITUDES_PEDIDOS VALUES ('WEB')
-- INSERT INTO SOLICITUDES_PEDIDOS VALUES ('EMAIL')
-- INSERT INTO SOLICITUDES_PEDIDOS VALUES ('TELEFONO')
-- INSERT INTO SOLICITUDES_PEDIDOS VALUES ('WHATSSAPP')
-- INSERT INTO SOLICITUDES_PEDIDOS VALUES ('REDES SOCIALES')
-- INSERT INTO SOLICITUDES_PEDIDOS VALUES ('TELEGRAM')
-- INSERT INTO SOLICITUDES_PEDIDOS VALUES ('PRESENCIAL')


--############################# TIPOS DOCUMENTOS ########################################################

-- INSERT INTO TIPOS_DOCUMENTOS VALUES ('DNI');
-- INSERT INTO TIPOS_DOCUMENTOS VALUES ('LIBRETA CIVICA');
-- INSERT INTO TIPOS_DOCUMENTOS VALUES ('CUIT');
-- INSERT INTO TIPOS_DOCUMENTOS VALUES ('CUIL');
-- INSERT INTO TIPOS_DOCUMENTOS VALUES ('PASAPORTE');

--############################# TIPOS ROLES #############################################################

-- INSERT INTO TIPOS_ROLES VALUES ('Cajero');
-- INSERT INTO TIPOS_ROLES VALUES ('Gerente');
-- INSERT INTO TIPOS_ROLES VALUES ('Supervisor');
-- INSERT INTO TIPOS_ROLES VALUES ('Encargado');
-- INSERT INTO TIPOS_ROLES VALUES ('Vendedor');
-- INSERT INTO TIPOS_ROLES VALUES ('Repartidor');
-- INSERT INTO TIPOS_ROLES VALUES ('Sub Encargado');
-- INSERT INTO TIPOS_ROLES VALUES ('Armador de Pedidos');
-- INSERT INTO TIPOS_ROLES VALUES ('Limpieza');
-- INSERT INTO TIPOS_ROLES VALUES ('Mantenimiento');
-- INSERT INTO TIPOS_ROLES VALUES ('Contador');
-- INSERT INTO TIPOS_ROLES VALUES ('Abogado');
-- INSERT INTO TIPOS_ROLES VALUES ('Publicista');
-- INSERT INTO TIPOS_ROLES VALUES ('Comunity Manager');

--############################# EMPLEADOS ###############################################################

-- INSERT INTO EMPLEADOS (ID_SUCURSAL,ID_TIPO_DOCUMENTO,ID_BARRIO,ID_TIPO_ROL,NOMBRE,APELLIDO,NRO_DOC,DIRECCION_EMPLEADO)
-- VALUES (1,1,1,1,'Yamila Belen','Echenique','39691077','Avenida Colon 1996');
-- INSERT INTO EMPLEADOS (ID_SUCURSAL,ID_TIPO_DOCUMENTO,ID_BARRIO,ID_TIPO_ROL,NOMBRE,APELLIDO,NRO_DOC,DIRECCION_EMPLEADO)
-- VALUES (1,1,2,2,'Guillermo Leonardo','Britos','39691072','Avenida Siempre Vivas 1996');
-- INSERT INTO EMPLEADOS (ID_SUCURSAL,ID_TIPO_DOCUMENTO,ID_BARRIO,ID_TIPO_ROL,NOMBRE,APELLIDO,NRO_DOC,DIRECCION_EMPLEADO)
-- VALUES (1,1,3,3,'Augusto Ezequiel','Gomez','39691258','San Martin 1656');
-- INSERT INTO EMPLEADOS (ID_SUCURSAL,ID_TIPO_DOCUMENTO,ID_BARRIO,ID_TIPO_ROL,NOMBRE,APELLIDO,NRO_DOC,DIRECCION_EMPLEADO)
-- VALUES (1,1,4,4,'Roberto Armando','Alvarez','11587456','General Paz 1569');
-- INSERT INTO EMPLEADOS (ID_SUCURSAL,ID_TIPO_DOCUMENTO,ID_BARRIO,ID_TIPO_ROL,NOMBRE,APELLIDO,NRO_DOC,DIRECCION_EMPLEADO)
-- VALUES (1,1,5,5,'Pedro Alberto','Salgado','22369854','Jujuy 956');
-- INSERT INTO EMPLEADOS (ID_SUCURSAL,ID_TIPO_DOCUMENTO,ID_BARRIO,ID_TIPO_ROL,NOMBRE,APELLIDO,NRO_DOC,DIRECCION_EMPLEADO)
-- VALUES (1,1,6,5,'Franco Emanuel','Ocampo','22333666','9 de julio 2456');
-- INSERT INTO EMPLEADOS (ID_SUCURSAL,ID_TIPO_DOCUMENTO,ID_BARRIO,ID_TIPO_ROL,NOMBRE,APELLIDO,NRO_DOC,DIRECCION_EMPLEADO)
-- VALUES (1,1,7,5,'Ernesto Ezequiel','Perez','23569874','Dean Funes 2556');
-- INSERT INTO EMPLEADOS (ID_SUCURSAL,ID_TIPO_DOCUMENTO,ID_BARRIO,ID_TIPO_ROL,NOMBRE,APELLIDO,NRO_DOC,DIRECCION_EMPLEADO)
-- VALUES (1,1,8,6,'Augusto Fabricio','Herrera','25698745','27 de Abril 1254');
-- INSERT INTO EMPLEADOS (ID_SUCURSAL,ID_TIPO_DOCUMENTO,ID_BARRIO,ID_TIPO_ROL,NOMBRE,APELLIDO,NRO_DOC,DIRECCION_EMPLEADO)
-- VALUES (1,1,9,6,'Florencia Lourdes','Alvarez','22366874','Avenida Bodereau 2587');
-- INSERT INTO EMPLEADOS (ID_SUCURSAL,ID_TIPO_DOCUMENTO,ID_BARRIO,ID_TIPO_ROL,NOMBRE,APELLIDO,NRO_DOC,DIRECCION_EMPLEADO)
-- VALUES (1,1,10,7,'Jose Marcelo','Gomez','25897456','Caseros 987');
-- INSERT INTO EMPLEADOS (ID_SUCURSAL,ID_TIPO_DOCUMENTO,ID_BARRIO,ID_TIPO_ROL,NOMBRE,APELLIDO,NRO_DOC,DIRECCION_EMPLEADO)
-- VALUES (1,1,11,8,'David Ernesto','Alvarez','37896545','Avenida Armada Argentina 1547');
-- INSERT INTO EMPLEADOS (ID_SUCURSAL,ID_TIPO_DOCUMENTO,ID_BARRIO,ID_TIPO_ROL,NOMBRE,APELLIDO,NRO_DOC,DIRECCION_EMPLEADO)
-- VALUES (1,1,12,9,'Anabel Florencia','Echenique','33259874','Rafael Nuñez 2556');
-- INSERT INTO EMPLEADOS (ID_SUCURSAL,ID_TIPO_DOCUMENTO,ID_BARRIO,ID_TIPO_ROL,NOMBRE,APELLIDO,NRO_DOC,DIRECCION_EMPLEADO)
-- VALUES (1,1,13,10,'Andres Federico','Alonso','43366874','Avenida Bodereau 2258');
-- INSERT INTO EMPLEADOS (ID_SUCURSAL,ID_TIPO_DOCUMENTO,ID_BARRIO,ID_TIPO_ROL,NOMBRE,APELLIDO,NRO_DOC,DIRECCION_EMPLEADO)
-- VALUES (1,1,14,11,'Javier Alejandro','Gomez','37891456','25 de Mayo 456');
-- INSERT INTO EMPLEADOS (ID_SUCURSAL,ID_TIPO_DOCUMENTO,ID_BARRIO,ID_TIPO_ROL,NOMBRE,APELLIDO,NRO_DOC,DIRECCION_EMPLEADO)
-- VALUES (1,1,15,12,'Damian Alexander','Alvarez','25897456','Rivera Indarte 2569');
-- INSERT INTO EMPLEADOS (ID_SUCURSAL,ID_TIPO_DOCUMENTO,ID_BARRIO,ID_TIPO_ROL,NOMBRE,APELLIDO,NRO_DOC,DIRECCION_EMPLEADO)
-- VALUES (1,1,16,13,'Lucia Florencia','Perez','35259874','Rafael Nuñez 1500');
-- INSERT INTO EMPLEADOS (ID_SUCURSAL,ID_TIPO_DOCUMENTO,ID_BARRIO,ID_TIPO_ROL,NOMBRE,APELLIDO,NRO_DOC,DIRECCION_EMPLEADO)
-- VALUES (1,1,16,13,'Victoria Anabel','Geysels','22569874','Brown 756');

-- --############################# PEDIDOS ###############################################################
-- ALTER TABLE PEDIDOS ALTER COLUMN HORA_PEDIDO VARCHAR (20);
-- INSERT INTO PEDIDOS (ID_PROVEEDOR,ID_SUCURSAL,ID_ENTREGA,ID_TIPO_SOLICITUD,ID_EMPLEADO_RECEPTOR,FECHA_PEDIDO,HORA_PEDIDO,FECHA_ENTREGA_PEDIDO,PLAZO_ENTREGA_PEDIDO)
-- VALUES(1,1,1,1,5,GETDATE(),'15:07',FORMAT('dd/MM/yyyy',GETDATE()) + 20, FORMAT('dd/MM/yyyy',GETDATE() + 30);
-- INSERT INTO PEDIDOS (ID_PROVEEDOR,ID_SUCURSAL,ID_ENTREGA,ID_TIPO_SOLICITUD,ID_EMPLEADO_RECEPTOR,FECHA_PEDIDO,HORA_PEDIDO,FECHA_ENTREGA_PEDIDO,PLAZO_ENTREGA_PEDIDO)
-- VALUES(1,1,1,1,6,GETDATE(),'15:27',(GETDATE() + 20),(GETDATE() + 30));
-- INSERT INTO PEDIDOS (ID_PROVEEDOR,ID_SUCURSAL,ID_ENTREGA,ID_TIPO_SOLICITUD,ID_EMPLEADO_RECEPTOR,FECHA_PEDIDO,HORA_PEDIDO,FECHA_ENTREGA_PEDIDO,PLAZO_ENTREGA_PEDIDO)
-- VALUES(1,1,1,1,7,GETDATE(),'15:25',(GETDATE() + 20),(GETDATE() + 30));
-- INSERT INTO PEDIDOS (ID_PROVEEDOR,ID_SUCURSAL,ID_ENTREGA,ID_TIPO_SOLICITUD,ID_EMPLEADO_RECEPTOR,FECHA_PEDIDO,HORA_PEDIDO,FECHA_ENTREGA_PEDIDO,PLAZO_ENTREGA_PEDIDO)
-- VALUES(1,1,1,1,5,GETDATE(),'9:27',(GETDATE() + 15),(GETDATE() + 21));
-- INSERT INTO PEDIDOS (ID_PROVEEDOR,ID_SUCURSAL,ID_ENTREGA,ID_TIPO_SOLICITUD,ID_EMPLEADO_RECEPTOR,FECHA_PEDIDO,HORA_PEDIDO,FECHA_ENTREGA_PEDIDO,PLAZO_ENTREGA_PEDIDO)
-- VALUES(1,1,1,1,6,GETDATE(),'13:34',(GETDATE() + 15),(GETDATE() + 35));
-- INSERT INTO PEDIDOS (ID_PROVEEDOR,ID_SUCURSAL,ID_ENTREGA,ID_TIPO_SOLICITUD,ID_EMPLEADO_RECEPTOR,FECHA_PEDIDO,HORA_PEDIDO,FECHA_ENTREGA_PEDIDO,PLAZO_ENTREGA_PEDIDO)
-- VALUES(1,1,1,1,7,GETDATE(),'8:27',(GETDATE() + 25),(GETDATE() + 40));
-- INSERT INTO PEDIDOS (ID_PROVEEDOR,ID_SUCURSAL,ID_ENTREGA,ID_TIPO_SOLICITUD,ID_EMPLEADO_RECEPTOR,FECHA_PEDIDO,HORA_PEDIDO,FECHA_ENTREGA_PEDIDO,PLAZO_ENTREGA_PEDIDO)
-- VALUES(1,1,1,1,7,GETDATE(),'10:16',(GETDATE() + 7),(GETDATE() + 10));
-- INSERT INTO PEDIDOS (ID_PROVEEDOR,ID_SUCURSAL,ID_ENTREGA,ID_TIPO_SOLICITUD,ID_EMPLEADO_RECEPTOR,FECHA_PEDIDO,HORA_PEDIDO,FECHA_ENTREGA_PEDIDO,PLAZO_ENTREGA_PEDIDO)
-- VALUES(1,1,1,1,5,GETDATE(),'11:17',(GETDATE() + 3),(GETDATE() + 5));
-- INSERT INTO PEDIDOS (ID_PROVEEDOR,ID_SUCURSAL,ID_ENTREGA,ID_TIPO_SOLICITUD,ID_EMPLEADO_RECEPTOR,FECHA_PEDIDO,HORA_PEDIDO,FECHA_ENTREGA_PEDIDO,PLAZO_ENTREGA_PEDIDO)
-- VALUES(1,1,1,1,6,GETDATE(),'12:54',(GETDATE() + 11),(GETDATE() + 22));

-- INSERT INTO PEDIDOS (ID_PROVEEDOR,ID_SUCURSAL,ID_ENTREGA,ID_TIPO_SOLICITUD,ID_EMPLEADO_RECEPTOR,FECHA_PEDIDO,HORA_PEDIDO,FECHA_ENTREGA_PEDIDO,PLAZO_ENTREGA_PEDIDO)
-- VALUES(1,1,1,1,6,GETDATE() - 1,'12:54',(GETDATE() + 11),(GETDATE() + 22));

-- INSERT INTO PEDIDOS (ID_PROVEEDOR,ID_SUCURSAL,ID_ENTREGA,ID_TIPO_SOLICITUD,ID_EMPLEADO_RECEPTOR,FECHA_PEDIDO,HORA_PEDIDO,FECHA_ENTREGA_PEDIDO,PLAZO_ENTREGA_PEDIDO)
-- VALUES(1,1,1,1,6,GETDATE() - 1,'12:54',(GETDATE() + 11),(GETDATE() + 22));

-- INSERT INTO PEDIDOS (ID_PROVEEDOR,ID_SUCURSAL,ID_ENTREGA,ID_TIPO_SOLICITUD,ID_EMPLEADO_RECEPTOR,FECHA_PEDIDO,HORA_PEDIDO,FECHA_ENTREGA_PEDIDO,PLAZO_ENTREGA_PEDIDO)
-- VALUES(1,1,1,1,6,GETDATE() - 1,'12:54',(GETDATE() + 11),(GETDATE() + 22));

-- INSERT INTO PEDIDOS (ID_PROVEEDOR,ID_SUCURSAL,ID_ENTREGA,ID_TIPO_SOLICITUD,ID_EMPLEADO_RECEPTOR,FECHA_PEDIDO,HORA_PEDIDO,FECHA_ENTREGA_PEDIDO,PLAZO_ENTREGA_PEDIDO)
-- VALUES(1,1,3,2,15,GETDATE() ,'12:54',(GETDATE()),(GETDATE()));


-- INSERT INTO PEDIDOS (ID_PROVEEDOR,ID_SUCURSAL,ID_ENTREGA,ID_TIPO_SOLICITUD,ID_EMPLEADO_RECEPTOR,FECHA_PEDIDO,HORA_PEDIDO,FECHA_ENTREGA_PEDIDO,PLAZO_ENTREGA_PEDIDO)
-- VALUES(1,1,3,2,15,GETDATE() ,'12:54',(GETDATE()),(GETDATE()));

-- INSERT INTO PEDIDOS (ID_PROVEEDOR,ID_SUCURSAL,ID_ENTREGA,ID_TIPO_SOLICITUD,ID_EMPLEADO_RECEPTOR,FECHA_PEDIDO,HORA_PEDIDO,FECHA_ENTREGA_PEDIDO,PLAZO_ENTREGA_PEDIDO)
-- VALUES(1,1,3,2,15,GETDATE() ,'12:54',(GETDATE()),(GETDATE()));

-- INSERT INTO PEDIDOS (ID_PROVEEDOR,ID_SUCURSAL,ID_ENTREGA,ID_TIPO_SOLICITUD,ID_EMPLEADO_RECEPTOR,FECHA_PEDIDO,HORA_PEDIDO,FECHA_ENTREGA_PEDIDO,PLAZO_ENTREGA_PEDIDO)
-- VALUES(1,1,3,2,15,GETDATE() ,'12:54',(GETDATE()),(GETDATE()));

-- INSERT INTO PEDIDOS (ID_PROVEEDOR,ID_SUCURSAL,ID_ENTREGA,ID_TIPO_SOLICITUD,ID_EMPLEADO_RECEPTOR,FECHA_PEDIDO,HORA_PEDIDO,FECHA_ENTREGA_PEDIDO,PLAZO_ENTREGA_PEDIDO)
-- VALUES(1,1,3,2,15,GETDATE() ,'12:54',(GETDATE()),(GETDATE()));

-- INSERT INTO PEDIDOS (ID_PROVEEDOR,ID_SUCURSAL,ID_ENTREGA,ID_TIPO_SOLICITUD,ID_EMPLEADO_RECEPTOR,FECHA_PEDIDO,HORA_PEDIDO,FECHA_ENTREGA_PEDIDO,PLAZO_ENTREGA_PEDIDO)
-- VALUES(1,1,3,2,15,GETDATE() ,'12:54',(GETDATE()),(GETDATE()));

-- INSERT INTO PEDIDOS (ID_PROVEEDOR,ID_SUCURSAL,ID_ENTREGA,ID_TIPO_SOLICITUD,ID_EMPLEADO_RECEPTOR,FECHA_PEDIDO,HORA_PEDIDO,FECHA_ENTREGA_PEDIDO,PLAZO_ENTREGA_PEDIDO)
-- VALUES(1,1,3,2,15,GETDATE() ,'12:54',(GETDATE()),(GETDATE()));

-- INSERT INTO PEDIDOS (ID_PROVEEDOR,ID_SUCURSAL,ID_ENTREGA,ID_TIPO_SOLICITUD,ID_EMPLEADO_RECEPTOR,FECHA_PEDIDO,HORA_PEDIDO,FECHA_ENTREGA_PEDIDO,PLAZO_ENTREGA_PEDIDO)
-- VALUES(1,1,3,2,15,GETDATE() ,'12:54',(GETDATE()),(GETDATE()));

-- INSERT INTO PEDIDOS (ID_PROVEEDOR,ID_SUCURSAL,ID_ENTREGA,ID_TIPO_SOLICITUD,ID_EMPLEADO_RECEPTOR,FECHA_PEDIDO,HORA_PEDIDO,FECHA_ENTREGA_PEDIDO,PLAZO_ENTREGA_PEDIDO)
-- VALUES(1,1,3,2,15,GETDATE() ,'12:54',(GETDATE()),(GETDATE()));

-- INSERT INTO PEDIDOS (ID_PROVEEDOR,ID_SUCURSAL,ID_ENTREGA,ID_TIPO_SOLICITUD,ID_EMPLEADO_RECEPTOR,FECHA_PEDIDO,HORA_PEDIDO,FECHA_ENTREGA_PEDIDO,PLAZO_ENTREGA_PEDIDO)
-- VALUES(1,1,3,2,15,GETDATE() ,'12:54',(GETDATE()),(GETDATE()));

-- INSERT INTO PEDIDOS (ID_PROVEEDOR,ID_SUCURSAL,ID_ENTREGA,ID_TIPO_SOLICITUD,ID_EMPLEADO_RECEPTOR,FECHA_PEDIDO,HORA_PEDIDO,FECHA_ENTREGA_PEDIDO,PLAZO_ENTREGA_PEDIDO)
-- VALUES(1,1,3,2,15,GETDATE() ,'12:54',(GETDATE()),(GETDATE()));


-- INSERT INTO PEDIDOS (ID_PROVEEDOR,ID_SUCURSAL,ID_ENTREGA,ID_TIPO_SOLICITUD,ID_EMPLEADO_RECEPTOR,FECHA_PEDIDO,HORA_PEDIDO,FECHA_ENTREGA_PEDIDO,PLAZO_ENTREGA_PEDIDO)
-- VALUES(1,1,3,2,14,GETDATE() ,'12:54',(GETDATE()),(GETDATE()));

-- INSERT INTO PEDIDOS (ID_PROVEEDOR,ID_SUCURSAL,ID_ENTREGA,ID_TIPO_SOLICITUD,ID_EMPLEADO_RECEPTOR,FECHA_PEDIDO,HORA_PEDIDO,FECHA_ENTREGA_PEDIDO,PLAZO_ENTREGA_PEDIDO)
-- VALUES(1,1,3,2,14,GETDATE() ,'12:54',(GETDATE()),(GETDATE()));

-- INSERT INTO PEDIDOS (ID_PROVEEDOR,ID_SUCURSAL,ID_ENTREGA,ID_TIPO_SOLICITUD,ID_EMPLEADO_RECEPTOR,FECHA_PEDIDO,HORA_PEDIDO,FECHA_ENTREGA_PEDIDO,PLAZO_ENTREGA_PEDIDO)
-- VALUES(1,1,3,2,14,GETDATE() ,'12:54',(GETDATE()),(GETDATE()));

-- INSERT INTO PEDIDOS (ID_PROVEEDOR,ID_SUCURSAL,ID_ENTREGA,ID_TIPO_SOLICITUD,ID_EMPLEADO_RECEPTOR,FECHA_PEDIDO,HORA_PEDIDO,FECHA_ENTREGA_PEDIDO,PLAZO_ENTREGA_PEDIDO)
-- VALUES(1,1,3,2,10,GETDATE() ,'12:54',(GETDATE()),(GETDATE()));

-- INSERT INTO PEDIDOS (ID_PROVEEDOR,ID_SUCURSAL,ID_ENTREGA,ID_TIPO_SOLICITUD,ID_EMPLEADO_RECEPTOR,FECHA_PEDIDO,HORA_PEDIDO,FECHA_ENTREGA_PEDIDO,PLAZO_ENTREGA_PEDIDO)
-- VALUES(1,1,3,2,10,GETDATE() ,'12:54',(GETDATE()),(GETDATE()));

-- INSERT INTO PEDIDOS (ID_PROVEEDOR,ID_SUCURSAL,ID_ENTREGA,ID_TIPO_SOLICITUD,ID_EMPLEADO_RECEPTOR,FECHA_PEDIDO,HORA_PEDIDO,FECHA_ENTREGA_PEDIDO,PLAZO_ENTREGA_PEDIDO)
-- VALUES(1,1,3,2,9,GETDATE() ,'12:54',(GETDATE()),(GETDATE()));

-- INSERT INTO PEDIDOS (ID_PROVEEDOR,ID_SUCURSAL,ID_ENTREGA,ID_TIPO_SOLICITUD,ID_EMPLEADO_RECEPTOR,FECHA_PEDIDO,HORA_PEDIDO,FECHA_ENTREGA_PEDIDO,PLAZO_ENTREGA_PEDIDO)
-- VALUES(1,1,3,2,1,GETDATE() ,'12:54',(GETDATE()),(GETDATE()));

-- INSERT INTO PEDIDOS (ID_PROVEEDOR,ID_SUCURSAL,ID_ENTREGA,ID_TIPO_SOLICITUD,ID_EMPLEADO_RECEPTOR,FECHA_PEDIDO,HORA_PEDIDO,FECHA_ENTREGA_PEDIDO,PLAZO_ENTREGA_PEDIDO)
-- VALUES(1,1,3,2,1,GETDATE() ,'12:54',(GETDATE()),(GETDATE()));

-- INSERT INTO PEDIDOS (ID_PROVEEDOR,ID_SUCURSAL,ID_ENTREGA,ID_TIPO_SOLICITUD,ID_EMPLEADO_RECEPTOR,FECHA_PEDIDO,HORA_PEDIDO,FECHA_ENTREGA_PEDIDO,PLAZO_ENTREGA_PEDIDO)
-- VALUES(1,1,3,2,11,GETDATE() ,'12:54',(GETDATE()),(GETDATE()));

-- INSERT INTO PEDIDOS (ID_PROVEEDOR,ID_SUCURSAL,ID_ENTREGA,ID_TIPO_SOLICITUD,ID_EMPLEADO_RECEPTOR,FECHA_PEDIDO,HORA_PEDIDO,FECHA_ENTREGA_PEDIDO,PLAZO_ENTREGA_PEDIDO)
-- VALUES(1,1,3,2,11,GETDATE() ,'12:54',(GETDATE()),(GETDATE()));

-- INSERT INTO PEDIDOS (ID_PROVEEDOR,ID_SUCURSAL,ID_ENTREGA,ID_TIPO_SOLICITUD,ID_EMPLEADO_RECEPTOR,FECHA_PEDIDO,HORA_PEDIDO,FECHA_ENTREGA_PEDIDO,PLAZO_ENTREGA_PEDIDO)
-- VALUES(1,1,3,2,11,GETDATE() ,'12:54',(GETDATE()),(GETDATE()));


-- INSERT INTO PEDIDOS (ID_PROVEEDOR,ID_SUCURSAL,ID_ENTREGA,ID_TIPO_SOLICITUD,ID_EMPLEADO_RECEPTOR,FECHA_PEDIDO,HORA_PEDIDO,FECHA_ENTREGA_PEDIDO,PLAZO_ENTREGA_PEDIDO)
-- VALUES(1,1,1,1,6,GETDATE() - 1,'12:54',(GETDATE() + 11),(GETDATE() + 22));



--############################# RUBROS ###############################################################

INSERT INTO RUBROS VALUES ('Electrico');
INSERT INTO RUBROS VALUES ('Carroceria');
INSERT INTO RUBROS VALUES ('Pintura');
INSERT INTO RUBROS VALUES ('Informatico');
INSERT INTO RUBROS VALUES ('Accesorios');
INSERT INTO RUBROS VALUES ('Seguridad');
INSERT INTO RUBROS VALUES ('Inteligencia');
INSERT INTO RUBROS VALUES ('Petrolero');
INSERT INTO RUBROS VALUES ('Motriz');
INSERT INTO RUBROS VALUES ('Ecologico');


--############################# MARCAS ###############################################################

INSERT INTO MARCAS VALUES ('Valeo');
INSERT INTO MARCAS VALUES ('Denso');
INSERT INTO MARCAS VALUES ('Mitsuba');
INSERT INTO MARCAS VALUES ('Daichi');
INSERT INTO MARCAS VALUES ('Hitachi');
INSERT INTO MARCAS VALUES ('Sony');
INSERT INTO MARCAS VALUES ('Honda');
INSERT INTO MARCAS VALUES ('Gates');
INSERT INTO MARCAS VALUES ('Yokohama');
INSERT INTO MARCAS VALUES ('KYB');
INSERT INTO MARCAS VALUES ('Spark');
INSERT INTO MARCAS VALUES ('Nos');
INSERT INTO MARCAS VALUES ('Exedy');


--############################# PRODUCTOS ###############################################################

INSERT INTO PRODUCTOS VALUES (7,1,'Optica','Delantera Izquierda',10559,500,30);
INSERT INTO PRODUCTOS VALUES (7,1,'Optica','Delantera Derecha', 10559,500,30);
INSERT INTO PRODUCTOS VALUES (7,1,'Optica','Trasera Izquierda',13695,500,30);
INSERT INTO PRODUCTOS VALUES (7,1,'Optica','Trasera Derecha',13695,500,30);
INSERT INTO PRODUCTOS VALUES (7,2,'Puerta','Delantera Izquierda',69700,20,5);
INSERT INTO PRODUCTOS VALUES (7,2,'Puerta','Delantera Derecha',69700,20,5);
INSERT INTO PRODUCTOS VALUES (7,2,'Puerta','Trasera Izquierda',49877,20,5);
INSERT INTO PRODUCTOS VALUES (7,2,'Puerta','Trasera Derecha',49877,20,5);
INSERT INTO PRODUCTOS VALUES (7,2,'Capot','6th Gen 1996-2000',95874,30,10);
INSERT INTO PRODUCTOS VALUES (7,2,'Luneta','6th Gen 1996-2000',93654,10,2);
INSERT INTO PRODUCTOS VALUES (7,2,'Parabrisas','6th Gen 1996-2000',125695,15,7);
INSERT INTO PRODUCTOS VALUES (7,5,'Llantas','Originales 90-00 Unidad',79582,100,20);

--############################# DETALLES PEDIDOS ###############################################################


EXEC sp_rename 'dbo.DETALLES_PEDIDOS.PRECIO_COMPRA', 'IMPORTE', 'COLUMN';

INSERT INTO DETALLES_PEDIDOS VALUES (1,1,1,10559); 
INSERT INTO DETALLES_PEDIDOS VALUES (1,1,1,10559); 
INSERT INTO DETALLES_PEDIDOS VALUES (1,1,1,10559); 
INSERT INTO DETALLES_PEDIDOS VALUES (1,1,1,10559); 
INSERT INTO DETALLES_PEDIDOS VALUES (1,1,1,10559);
INSERT INTO DETALLES_PEDIDOS VALUES (2,3,5,10559); 
INSERT INTO DETALLES_PEDIDOS VALUES (2,3,7,10559); 
INSERT INTO DETALLES_PEDIDOS VALUES (2,3,4,10559); 
INSERT INTO DETALLES_PEDIDOS VALUES (2,3,1,10559);
INSERT INTO DETALLES_PEDIDOS VALUES (3,9,2,53556); 
INSERT INTO DETALLES_PEDIDOS VALUES (3,12,1,128000); 
INSERT INTO DETALLES_PEDIDOS VALUES (3,1,4,13500);
INSERT INTO DETALLES_PEDIDOS VALUES (5,1,1,10559); 
INSERT INTO DETALLES_PEDIDOS VALUES (5,1,1,10559); 
INSERT INTO DETALLES_PEDIDOS VALUES (5,1,1,10559); 





