USE AUTOMOTRIZ;

-- Creates the login AbolrousHazem with password '340$Uuxwp7Mcxo7Khy'.  
CREATE LOGIN DAVID_DIFRANCESCO   
    WITH PASSWORD = 'y(Mg(Sh#Hl-Mp+Rn%VyXi';  
GO  

--DROP LOGIN GroupTPLCI2022;

-- Creates a database user for the login created above.  
CREATE USER DAVID_DIFRANCESCO FOR LOGIN DAVID_DIFRANCESCO;  
GO

--DROP USER GroupTPLCI2022;

--CREATE ROLE GroupTPLCI2022 AUTHORIZATION db_datareader ;


ALTER ROLE GroupTPLCI2022 ADD MEMBER DAVID_DIFRANCESCO;

--GRANT SELECT TO Automotriz  GroupTPLCI2022;

USE Automotriz;
GRANT VIEW DEFINITION  TO GroupTPLCI2022;
GO


USE Automotriz;
REVOKE VIEW DEFINITION  TO GroupTPLCI2022;
GO

SELECT * FROM PAISES;

USE Automotriz;
GRANT SELECT TO GroupTPLCI2022;
GO


INSERT INTO GUILLEE_TEST VALUES ('TEST');

DROP TABLE GUILLEE_TEST; 


CREATE LOGIN VICTOR WITH PASSWORD = '123456';

USE Automotriz

CREATE USER VICTOR FOR LOGIN VICTOR;

ALTER ROLE db_datareader ADD MEMBER VICTOR

--INSERT INTO GUI

USE Automotriz;


CREATE TABLE GUILLEE_TEST 
(
    NOMBRE VARCHAR (20)







)



DROP TABLE GUILLEE_TEST;

SELECT * FROM CLIENTES;


INSERT INTO PAISES VALUES ('ARGENTINA');

DROP TABLE PAISES ;

DROP TABLE BARRIOS;

USE Automotriz;
GRANT INSERT TO VICTOR;
GO

USE Automotriz;
REVOKE INSERT TO VICTOR;
GO


SELECT * FROM PAISES;

DELETE FROM PAISES WHERE ID_PAIS = 1;


UPDATE PAISES SET NOMBRE = 'BRASIL' WHERE ID_PAIS = 2;