USE AUTOMOTRIZ;

CREATE TABLE USERS 
(
    ID_USER INT  IDENTITY(1,1),
    NOMBRE VARCHAR (100),
    CONTRASEÑA  VARCHAR (100),
    EMAIL VARCHAR (100),
    ESADMIN BIT 
    CONSTRAINT PK_USERS PRIMARY KEY (ID_USER) 

)

SELECT * FROM USERS;