CREATE DATABASE AUTOMOTRIZ;

USE AUTOMOTRIZ;

CREATE TABLE PAISES
(
    ID_PAIS INT IDENTITY(1,1),
    NOMBRE VARCHAR (30),
    CONSTRAINT PK_PAIS PRIMARY KEY (ID_PAIS)


);

CREATE TABLE PROVINCIAS
(
    ID_PROVINCIA INT IDENTITY (1,1),
    ID_PAIS INT,
    NOMBRE VARCHAR (50)
    CONSTRAINT PK_PROVINCIA PRIMARY KEY (ID_PROVINCIA),
    CONSTRAINT FK_PAISES_PROVINCIAS FOREIGN KEY (ID_PAIS) REFERENCES PAISES (ID_PAIS)


);


CREATE TABLE CIUDADES
(
    ID_CIUDAD INT IDENTITY (1,1),
    ID_PROVINCIA INT,
    NOMBRE VARCHAR (50)
    CONSTRAINT PK_CIUDAD PRIMARY KEY (ID_CIUDAD),
    CONSTRAINT FK_PROVINCIAS_CIUDADES FOREIGN KEY (ID_PROVINCIA) REFERENCES PROVINCIAS (ID_PROVINCIA)

);


CREATE TABLE BARRIOS
(
    ID_BARRIO INT IDENTITY (1,1),
    ID_CIUDAD INT,
    NOMBRE VARCHAR (50)
    CONSTRAINT PK_BARRIO PRIMARY KEY (ID_BARRIO)
    CONSTRAINT FK_CIUDADES_BARRIOS FOREIGN KEY (ID_CIUDAD) REFERENCES CIUDADES (ID_CIUDAD)

);

CREATE TABLE PROVEEDORES 
(
    ID_PROVEEDOR INT IDENTITY (1,1),
    ID_BARRIO INT,
    NOMBRE VARCHAR (30),
    DIRECCION_PROVEEDOR VARCHAR (50),
    CONSTRAINT PK_PROVEEDOR PRIMARY KEY (ID_PROVEEDOR),
    CONSTRAINT FK_BARRIO_PROVEEDOR FOREIGN KEY (ID_BARRIO) REFERENCES BARRIOS (ID_BARRIO)

);

CREATE TABLE TIPOS_CONTACTOS
(
    ID_TIPO_CONTACTO INT IDENTITY (1,1),
    DESCRIPCION VARCHAR (30),
    CONSTRAINT PK_TIPO_CONTACTO PRIMARY KEY (ID_TIPO_CONTACTO)

);


CREATE TABLE CONTACTOS_PROVEEDORES
(
    ID_CONTACTO_PROVEEDOR INT IDENTITY (1,1),
    ID_TIPO_CONTACTO INT,
    ID_PROVEEDOR INT,
    CONTACTO VARCHAR (30),
    CONSTRAINT PK_CONTACTO_PROVEEDOR PRIMARY KEY (ID_CONTACTO_PROVEEDOR),
    CONSTRAINT FK_TIPO_CONTACTO_CONTACTO_PROVEEDOR FOREIGN KEY (ID_TIPO_CONTACTO) REFERENCES TIPOS_CONTACTOS (ID_TIPO_CONTACTO),
    CONSTRAINT FK_PROVEEDOR_CONTACTO_PROVEEDOR FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDORES (ID_PROVEEDOR)
); 

CREATE TABLE SUCURSALES
(
    ID_SUCURSAL INT IDENTITY (1,1),
    ID_BARRIO INT,
    DIRECCION_SUCURSAL VARCHAR (50),
    CONSTRAINT PK_SUCURSAL PRIMARY KEY (ID_SUCURSAL),
    CONSTRAINT FK_BARRIO_SUCURSAL FOREIGN KEY (ID_BARRIO) REFERENCES BARRIOS (ID_BARRIO)
);



CREATE TABLE CONTACTOS_SUCURSALES
(
    ID_CONTACTO_SUCURSAL INT IDENTITY (1,1),
    ID_SUCURSAL INT,
    ID_TIPO_CONTACTO INT, 
    CONTACTO VARCHAR (50),
    CONSTRAINT PK_CONTACTO_SUCURSAL PRIMARY KEY (ID_CONTACTO_SUCURSAL),
    CONSTRAINT FK_SUCURSAL_CONTACTO_SUCURSAL FOREIGN KEY (ID_SUCURSAL) REFERENCES SUCURSALES (ID_SUCURSAL),
    CONSTRAINT FK_TIPO_CONTACTO_CONTACTO_SUCURSAL FOREIGN KEY (ID_TIPO_CONTACTO) REFERENCES TIPOS_CONTACTOS (ID_TIPO_CONTACTO)

);


CREATE TABLE TIPOS_DOCUMENTOS 
(
    ID_TIPO_DOCUMENTO INT IDENTITY (1,1),
    DESCRIPCION VARCHAR  (30),
    CONSTRAINT PK_TIPO_DOCUMENTO PRIMARY KEY (ID_TIPO_DOCUMENTO)

);



CREATE TABLE TIPOS_ROLES
(
    ID_TIPO_ROL INT IDENTITY (1,1),
    PUESTO VARCHAR (30),
    CONSTRAINT PK_TIPO_ROL PRIMARY KEY (ID_TIPO_ROL)

);

CREATE TABLE CLIENTES 
(
    ID_CLIENTE INT IDENTITY (1,1),
    ID_TIPO_DOCUMENTO INT,
    ID_BARRIO INT,
    ID_TIPO_CONTACTO INT,
    NOMBRE VARCHAR (20),
    APELLIDO VARCHAR (20),
    RAZON_SOCIAL VARCHAR (30)
    CONSTRAINT PK_CLIENTE PRIMARY KEY (ID_CLIENTE),
    CONSTRAINT FK_TIPO_DOCUMENTO_CLIENTE FOREIGN KEY (ID_TIPO_DOCUMENTO) REFERENCES TIPOS_DOCUMENTOS (ID_TIPO_DOCUMENTO),
    CONSTRAINT FK_BARRIO_CLIENTE FOREIGN KEY (ID_BARRIO) REFERENCES BARRIOS (ID_BARRIO),
    CONSTRAINT FK_TIPO_CONTACTO_CLIENTE FOREIGN KEY (ID_TIPO_CONTACTO) REFERENCES TIPOS_CONTACTOS (ID_TIPO_CONTACTO)
);

CREATE TABLE TIPOS_CLIENTES 
(
    ID_TIPO_CLIENTE INT IDENTITY (1,1),
    ID_CLIENTE INT,
    TIPO_CLIENTE VARCHAR (30),
    CONSTRAINT PK_TIPO_CLIENTE PRIMARY KEY (ID_TIPO_CLIENTE),
    CONSTRAINT FK_CLIENT_TIPO_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE)

);


CREATE TABLE EMPLEADOS 
(
    ID_EMPLEADO INT IDENTITY (1,1),
    ID_SUCURSAL INT,
    ID_TIPO_DOCUMENTO INT,
    ID_BARRIO INT,
    ID_TIPO_ROL INT,
    NOMBRE VARCHAR (50),
    APELLIDO VARCHAR (50),
    NRO_DOC VARCHAR (50),
    DIRECCION_EMPLEADO VARCHAR (50),
    CONSTRAINT PK_EMPLEADO PRIMARY KEY (ID_EMPLEADO),
    CONSTRAINT FK_SUCURSAL_EMPLEADO FOREIGN KEY (ID_SUCURSAL) REFERENCES SUCURSALES (ID_SUCURSAL),
    CONSTRAINT FK_TIPO_DOCUMENTO_EMPLEADO FOREIGN KEY (ID_TIPO_DOCUMENTO) REFERENCES TIPOS_DOCUMENTOS (ID_TIPO_DOCUMENTO),
    CONSTRAINT FK_TIPO_ROL_EMPLEADO FOREIGN KEY (ID_TIPO_ROL) REFERENCES TIPOS_ROLES (ID_TIPO_ROL),
    CONSTRAINT FK_BARRIO_EMPLEADO FOREIGN KEY (ID_BARRIO) REFERENCES BARRIOS (ID_BARRIO)

);

CREATE TABLE ENTREGAS 
(
    ID_ENTREGA INT IDENTITY (1,1),
    DESCRIPCION VARCHAR (50),
    CONSTRAINT PK_ENTREGA PRIMARY KEY (ID_ENTREGA) 

);

CREATE TABLE SOLICITUDES_PEDIDOS
(
    ID_SOLICITUD INT IDENTITY (1,1),
    SOLICITADO_VIA VARCHAR (50),
    CONSTRAINT PK_SOLICITUD_PEDIDO PRIMARY KEY (ID_SOLICITUD)

);

CREATE TABLE PEDIDOS
(
    ID_PEDIDO INT IDENTITY (1,1),
    ID_PROVEEDOR INT,
    ID_SUCURSAL INT,
    ID_ENTREGA INT,
    ID_TIPO_SOLICITUD INT,
    ID_EMPLEADO_RECEPTOR INT,
    FECHA_PEDIDO DATETIME,
    HORA_PEDIDO DATETIME,
    FECHA_ENTREGA_PEDIDO DATETIME,
    PLAZO_ENTREGA_PEDIDO VARCHAR (20),
    CONSTRAINT PK_PEDIDO PRIMARY KEY (ID_PEDIDO),
    CONSTRAINT FK_PROVEEDOR_PEDIDO FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDORES (ID_PROVEEDOR),
    CONSTRAINT FK_SUCURSAL_PEDIDO FOREIGN KEY (ID_SUCURSAL) REFERENCES SUCURSALES (ID_SUCURSAL),
    CONSTRAINT FK_ENTREGA_PEDIDO FOREIGN KEY (ID_ENTREGA) REFERENCES ENTREGAS (ID_ENTREGA),
    CONSTRAINT FK_TIPO_SOLICITUD_PEDIDO FOREIGN KEY (ID_TIPO_SOLICITUD) REFERENCES SOLICITUDES_PEDIDOS (ID_SOLICITUD),
    CONSTRAINT FK_EMPLEADO_PEDIDO FOREIGN KEY (ID_EMPLEADO_RECEPTOR) REFERENCES EMPLEADOS (ID_EMPLEADO)

);

CREATE TABLE MARCAS 
(
    ID_MARCA INT IDENTITY (1,1),
    MARCA VARCHAR (50),
    CONSTRAINT PK_MARCA PRIMARY KEY (ID_MARCA)

);

CREATE TABLE RUBROS
(
    ID_RUBRO INT IDENTITY (1,1),
    NOMBRE_RUBRO VARCHAR  (50),
    CONSTRAINT PK_RUBRO PRIMARY KEY (ID_RUBRO)

);


CREATE TABLE PRODUCTOS
(
    ID_PRODUCTO INT IDENTITY (1,1),
    ID_MARCA INT,
    ID_RUBRO INT, 
    NOMBRE VARCHAR (30),
    DESCRIPCION VARCHAR (30),
    PRECIO MONEY,
    STOCK INT,
    STOCK_MINIMO INT,
    CONSTRAINT PK_PRODUCTO PRIMARY KEY (ID_PRODUCTO),
    CONSTRAINT FK_MARCA FOREIGN KEY (ID_MARCA) REFERENCES MARCAS (ID_MARCA),
    CONSTRAINT FK_RUBRO FOREIGN KEY (ID_RUBRO) REFERENCES RUBROS (ID_RUBRO)
);

CREATE TABLE TIPOS_PRODUCTOS
(
    ID_TIPO_PRODUCTO INT IDENTITY (1,1),
    ID_PRODUCTO INT,
    TIPO_PRODUCTO VARCHAR (50),
    CONSTRAINT PK_TIPO_PRODUCTO PRIMARY KEY (ID_TIPO_PRODUCTO),
    CONSTRAINT FK_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS (ID_PRODUCTO)

);




CREATE TABLE DETALLES_PEDIDOS
(
    ID_DETALLE_PEDIDO INT IDENTITY (1,1),
    ID_PRODUCTO INT,
    ID_PEDIDO INT, 
    CANTIDAD INT, 
    PRECIO_COMPRA DECIMAL (10,2),
    CONSTRAINT PK_DETALLE_PEDIDO PRIMARY KEY (ID_DETALLE_PEDIDO),
    CONSTRAINT FK_PRODUCTO_DETALLE_PEDIDO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS (ID_PRODUCTO),
    CONSTRAINT FK_PEDIDO_DETALLE_PEDIDO FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS (ID_PEDIDO),

);



CREATE TABLE CONTACTOS_EMPLEADOS
(
    ID_CONTACTO_EMPLEADO INT IDENTITY (1,1),
    ID_EMPLEADO INT,
    ID_TIPO_CONTACTO INT,
    CONTACTO VARCHAR (50),
    CONSTRAINT PK_CONTACTO_EMPLEADO PRIMARY KEY (ID_CONTACTO_EMPLEADO),
    CONSTRAINT FK_EMPLEADO_CONTACTO_EMPLEADO FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS (ID_EMPLEADO),
    CONSTRAINT FK_TIPO_CONTACTO_CONTACTO_EMPLEADO FOREIGN KEY (ID_TIPO_CONTACTO) REFERENCES TIPOS_CONTACTOS (ID_TIPO_CONTACTO)

);

CREATE TABLE FORMAS_PAGOS
(
    ID_FORMA_PAGO INT IDENTITY (1,1),
    FORMA_PAGO VARCHAR (30),
    CONSTRAINT PK_FORMA_PAGO PRIMARY KEY (ID_FORMA_PAGO)

);

CREATE TABLE PEDIDOS_FORMAS_PAGOS
(
    ID_PEDIDO_FORMA_PAGO INT IDENTITY (1,1),
    ID_PEDIDO INT,
    ID_FORMA_PAGO INT,
    MONTO_ABONADO MONEY,
    CONSTRAINT PK_ID_PEDIDO_FORMA_PAGO PRIMARY KEY (ID_PEDIDO_FORMA_PAGO),
    CONSTRAINT FK_ID_PEDIDO_FORMA_PAGO FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS (ID_PEDIDO),
    CONSTRAINT FK_FORMA_PAGO FOREIGN KEY (ID_FORMA_PAGO) REFERENCES FORMAS_PAGOS (ID_FORMA_PAGO) 

);




