USE VIVERO_FENIX;

--31

/*Listado de clientes mostrando apellido y nombre, calle y número*/

SELECT NOMBRE + ' ' +  APELLIDO AS 'NOMBRE COMPLETO', COD_CALLE , ALTURA 
FROM CLIENTES

--32

/*Listado de clientes mostrando apellido, nombre y localidad a la que pertenece*/

SELECT C.COD_CLIENTE,C.NOMBRE + ' ' + C.APELLIDO AS 'FULL NAME',L.NOMBRE AS 'LOCALIDAD'
FROM CLIENTES C ,LOCALIDADES L
WHERE C.COD_LOCALIDAD  = L.COD_LOCALIDAD;

--33

SELECT C.APELLIDO,C.NOMBRE,B.COD_BARRIO
FROM CLIENTES C, BARRIOS B
WHERE C.COD_CLIENTE = B.COD_BARRIO;

--34

SELECT *
FROM FACTURAS;

SELECT F.NRO_FACTURA,F.COD_CLIENTE,F.COD_FORMA_PAGO
FROM FACTURAS F, CLIENTES C
WHERE F.NRO_FACTURA = F.COD_CLIENTE AND F.COD_FORMA_PAGO = 1
ORDER BY F.COD_CLIENTE;

--35


SELECT *
FROM TIPOS_PLANTAS;

SELECT *
FROM PLANTAS;

SELECT P.COD_PLANTA,TP.COD_TIPO_PLANTA,TP.NOMBRE,P.PRECIO,P.STOCK
FROM PLANTAS P, TIPOS_PLANTAS TP
WHERE TP.COD_TIPO_PLANTA = 5;

--36


SELECT C.NOMBRE,C.APELLIDO, L.COD_LOCALIDAD,L.NOMBRE
FROM CLIENTES C, LOCALIDADES L
WHERE L.NOMBRE = 'AREQUITO';

--37

SELECT COD_CONDICION_IVA
FROM CLIENTES;

SELECT COD_CONDICION_IVA,DESCRIPCION 
FROM CONDICIONES_IVA
WHERE COD_CONDICION_IVA = 3;

SELECT  *
FROM CLIENTES;


SELECT DISTINCT C.NOMBRE,C.APELLIDO, CIVA.COD_CONDICION_IVA,CIVA.DESCRIPCION,L.COD_LOCALIDAD,L.NOMBRE 
FROM CLIENTES C, CONDICIONES_IVA CIVA, LOCALIDADES L
WHERE CIVA.COD_CONDICION_IVA = 3 AND C.COD_LOCALIDAD = L.COD_LOCALIDAD
ORDER BY L.NOMBRE ;


--38

SELECT COD_LOCALIDAD, NOMBRE
FROM LOCALIDADES;

SELECT C.COD_CLIENTE,C.NOMBRE,C.APELLIDO,C.COD_LOCALIDAD,L.COD_LOCALIDAD,L.NOMBRE 
FROM CLIENTES C , LOCALIDADES L
WHERE C.COD_LOCALIDAD = L.COD_LOCALIDAD AND (L.COD_LOCALIDAD = 1 OR C.APELLIDO LIKE 'A%');

--39

SELECT *
FROM LOCALIDADES;

SELECT C.NOMBRE,C.APELLIDO,C.COD_LOCALIDAD, L.COD_LOCALIDAD,L.NOMBRE
FROM CLIENTES C, LOCALIDADES L
WHERE L.COD_LOCALIDAD = C.COD_LOCALIDAD AND (L.COD_LOCALIDAD = 1
OR L.COD_LOCALIDAD = 2 OR L.COD_LOCALIDAD = 4);

--40

SELECT COD_LOCALIDAD,NOMBRE
FROM LOCALIDADES;

SELECT C.COD_CLIENTE,C.NOMBRE + ' ' + C.APELLIDO AS 'FULL NAME',/*C.COD_LOCALIDAD,L.COD_LOCALIDAD,*/ L.NOMBRE AS 'LOCALIDAD'
FROM CLIENTES C, LOCALIDADES L
WHERE L.COD_LOCALIDAD = C.COD_LOCALIDAD
AND L.NOMBRE != 'AREQUITO' AND L.NOMBRE != 'MERLO';

--41 --DUDAS

SELECT NOMBRE
FROM BARRIOS;

SELECT NOMBRE
FROM LOCALIDADES;

SELECT C.NOMBRE + ' ' + C.APELLIDO AS 'FULL NAME',B.NOMBRE AS 'BARRIO',L.NOMBRE AS 'LOCALIDAD'
FROM CLIENTES C, BARRIOS B , LOCALIDADES L
WHERE L.COD_LOCALIDAD = C.COD_LOCALIDAD 
AND B.COD_BARRIO = C.COD_BARRIO 
AND  (L.NOMBRE = 'CORDOBA' 
OR C.APELLIDO NOT LIKE '[D-P]%')
ORDER BY C.COD_BARRIO;

--42 -- DUDAS

SELECT * 
FROM PLANTAS;


SELECT DF.COD_DETALLE,P.DESCRIPCION,DF.CANTIDAD * P.PRECIO  AS 'PRECIO FINAL' 
FROM DETALLES_FACTURAS DF ,PLANTAS P
WHERE (P.COD_PLANTA = DF.COD_PLANTA)
ORDER BY 'PRECIO FINAL' DESC;

--43














