CREATE DATABASE PERSONAL_DOCENTE;

USE PERSONAL_DOCENTE;

CREATE TABLE DOCENTES 
(
    legajo_docente int,
    nombre varchar (20),
    apellid varchar (20),
    email varchar (20),

);

ALTER TABLE DOCENTES ALTER COLUMN legajo_docente int NOT NULL;

ALTER TABLE DOCENTES ADD CONSTRAINT PK_DOCENTE PRIMARY KEY (legajo_docente);

CREATE TABLE TITULOS
(
    id_titulo int,
    descripcion varchar (30),


);

ALTER TABLE TITULOS ALTER COLUMN id_titulo int NOT NULL;

ALTER TABLE TITULOS ADD CONSTRAINT PK_TITULO PRIMARY KEY (id_titulo);

ALTER TABLE DOCENTES ADD id_titulo int;

ALTER TABLE DOCENTES ALTER COLUMN id_titulo int;

ALTER TABLE DOCENTES ADD CONSTRAINT FK_TTITULOS_DOCENTES FOREIGN KEY (id_titulo)
REFERENCES TITULOS (id_titulo);

ALTER TABLE DOCENTES DROP CONSTRAINT FK_TTITULOS_DOCENTES;

ALTER TABLE TITULOS DROP CONSTRAINT PK_TITULO;