CREATE DATABASE PROGRAMACION_SEGUNDO_CUATRIMESTRE;
 
 USE PROGRAMACION_SEGUNDO_CUATRIMESTRE;

CREATE PROCEDURE [dbo].[SP_CONSULTAR_MODELOS]
@nombre varchar(40)
AS
BEGIN
SELECT * FROM T_MODELOS t WHERE t.nombre = @nombre;
END