USE VIVERO_FENIX;

--1)

SELECT COD_CLIENTE, APELLIDO, NOMBRE
FROM CLIENTES
ORDER BY COD_CLIENTE 

--2

SELECT COD_CLIENTE, APELLIDO,NOMBRE
FROM CLIENTES
ORDER BY APELLIDO,NOMBRE ASC

--3

SELECT COD_PLANTA,DESCRIPCION,PRECIO
FROM PLANTAS
ORDER BY COD_PLANTA DESC

--4

SELECT STOCK AS 'STOCK ACTUAL,NOMBRE PLANTA' , DESCRIPCION   AS 'DESCRIPCION' 
FROM PLANTAS
ORDER BY DESCRIPCION

--5

SELECT NOMBRE
FROM LOCALIDADES
ORDER BY NOMBRE ASC

--6

SELECT APELLIDO + ' ' + NOMBRE AS 'NOMBRE COMPLETO', COD_CLIENTE
FROM CLIENTES

--7

SELECT COD_PLANTA, DESCRIPCION,COD_TIPO_PLANTA,STOCK,
( PRECIO - ((PRECIO * 10) / 100 ) )  AS 'PRECIO_FINAL' 
FROM PLANTAS
ORDER BY PRECIO 

--8

SELECT STOCK 
FROM PLANTAS

SELECT (STOCK * 15) AS 'STOCK TOTAL PLANTAS'
FROM PLANTAS

--9

SELECT DISTINCT APELLIDO
FROM CLIENTES;


SELECT COD_CLIENTE,NOMBRE,APELLIDO 
FROM CLIENTES
WHERE DEUDOR = 'S';

--10

SELECT STOCK
FROM PLANTAS 
ORDER BY STOCK

SELECT STOCK
FROM PLANTAS
WHERE STOCK > 20
ORDER BY STOCK;

--11
SELECT STOCK,COD_PLANTA
FROM PLANTAS
ORDER BY COD_PLANTA;

SELECT STOCK,COD_PLANTA
FROM PLANTAS
WHERE STOCK != 30
ORDER BY COD_PLANTA;

--12

SELECT FECHA
FROM FACTURAS;


SELECT FECHA
FROM FACTURAS
WHERE FECHA > '09/06/01'

--13

SELECT STOCK
FROM PLANTAS;

SELECT STOCK
FROM PLANTAS 
WHERE STOCK < 10;

--14

SELECT FECHA
FROM FACTURAS
--WHERE FECHA >= '01/06/08' AND FECHA <= '01/06/09' 
WHERE FECHA BETWEEN '01/06/08' AND '01/06/09' 

--15

SELECT PRECIO
FROM PLANTAS;

SELECT COD_PLANTA,DESCRIPCION,COD_TIPO_PLANTA,PRECIO,STOCK
FROM PLANTAS
--WHERE PRECIO >= 20 AND PRECIO <= 70
WHERE PRECIO BETWEEN 20 AND 70;

--16

SELECT STOCK
FROM PLANTAS;

SELECT DESCRIPCION,STOCK,PRECIO
FROM PLANTAS
WHERE STOCK >= 5 AND STOCK <= 10
--WHERE STOCK BETWEEN 5 AND 10;

--17

SELECT APELLIDO
FROM CLIENTES;

SELECT APELLIDO
FROM CLIENTES
WHERE APELLIDO LIKE 'f%';

--18

SELECT NOMBRE
FROM CLIENTES;

SELECT NOMBRE
FROM CLIENTES
WHERE NOMBRE LIKE '%u%';

--19

SELECT APELLIDO
FROM CLIENTES
WHERE APELLIDO NOT LIKE '[A-C]%';

--20

SELECT APELLIDO
FROM CLIENTES
WHERE APELLIDO LIKE '%EZ'

--21

SELECT APELLIDO
FROM CLIENTES
WHERE APELLIDO NOT LIKE 'P%'

--22

SELECT APELLIDO
FROM CLIENTES;

SELECT APELLIDO
FROM CLIENTES
WHERE APELLIDO NOT LIKE '[P-Z]%';

--23

SELECT TELEFONO
FROM CLIENTES;

SELECT NOMBRE, APELLIDO, TELEFONO
FROM CLIENTES
WHERE TELEFONO IS NULL;

--24

SELECT EMAIL
FROM CLIENTES;

SELECT APELLIDO, NOMBRE, TELEFONO
FROM CLIENTES
WHERE EMAIL IS NOT NULL;

--25

SELECT TELEFONO
FROM CLIENTES;


SELECT APELLIDO,NOMBRE,TELEFONO
FROM CLIENTES
WHERE TELEFONO IS NOT NULL;

--26

SELECT DESCRIPCION,PRECIO
FROM PLANTAS;

SELECT DESCRIPCION,PRECIO
FROM PLANTAS
WHERE DESCRIPCION LIKE 'R%' AND PRECIO > 7;

--27

SELECT PRECIO
FROM PLANTAS
WHERE PRECIO < 50 OR PRECIO > 100;

SELECT (((PRECIO * 10) / 100) + PRECIO)  AS 'PRECIO FINAL'
FROM PLANTAS
WHERE PRECIO < 50 OR PRECIO > 100 ;

--28

SELECT APELLIDO,NOMBRE,TELEFONO,EMAIL
FROM CLIENTES;


SELECT APELLIDO,NOMBRE,TELEFONO,EMAIL 
FROM CLIENTES
WHERE EMAIL IS NOT NULL OR TELEFONO IS NOT NULL;

--29
--REVISARRRRRR 
SELECT PRECIO 
FROM CLIENTES;

SELECT STOCK,PRECIO, PRECIO * STOCK AS "PRECIO STOCK TOTAL"
FROM PLANTAS
WHERE (PRECIO * STOCK) < 10000;

SELECT DESCRIPCION,STOCK,PRECIO,(PRECIO * STOCK) AS 'STOCK*PRECIO'
FROM PLANTAS
WHERE DESCRIPCION NOT LIKE '[M-N]%' AND DESCRIPCION NOT LIKE 'P%'
OR PRECIO > 50 AND (STOCK*PRECIO) < 1000;

SELECT STOCK
FROM PLANTAS;

SELECT DESCRIPCION,STOCK,PRECIO,(PRECIO * STOCK) AS 'STOCK*PRECIO'
FROM PLANTAS
WHERE (DESCRIPCION NOT LIKE '[M-N]%' AND DESCRIPCION NOT LIKE 'P%')
OR (PRECIO > 50 AND (STOCK*PRECIO) < 10000);


USE ESCUELA;

SELECT * FROM
ALUMNOS;

ALTER TABLE ALUMNOS ADD CONSTRAINT PK_ALUMNO PRIMARY KEY (legajo);

ALTER TABLE ALUMNOS
DROP CONSTRAINT PK_ALUMNO;


